import type { ExerciseLibrary } from "@/types/exercise";

export const exerciseLibrary: ExerciseLibrary = [
  {
    id: "barbell-back-squat",
    name: "Barbell Back Squat",
    blockKind: "compound",
    movementPattern: "squat",
    compatibleSplitDayTypes: ["legs", "lower", "full-body", "athletic-hybrid"],
    goalTags: ["strength", "athleticism", "general"],
    restrictionTags: ["knee-stress"],
  },
  {
    id: "conventional-deadlift",
    name: "Conventional Deadlift",
    blockKind: "compound",
    movementPattern: "hinge",
    compatibleSplitDayTypes: ["legs", "lower", "back", "full-body", "athletic-hybrid"],
    goalTags: ["strength", "athleticism", "general"],
    restrictionTags: ["low-back-stress"],
  },
  {
    id: "barbell-bench-press",
    name: "Barbell Bench Press",
    blockKind: "compound",
    movementPattern: "push-horizontal",
    compatibleSplitDayTypes: ["push", "chest", "upper", "full-body"],
    goalTags: ["strength", "aesthetics", "general"],
  },
  {
    id: "overhead-press",
    name: "Overhead Press",
    blockKind: "compound",
    movementPattern: "push-vertical",
    compatibleSplitDayTypes: ["push", "shoulders", "upper", "full-body"],
    goalTags: ["strength", "athleticism", "general"],
    restrictionTags: ["overhead"],
  },
  {
    id: "barbell-row",
    name: "Barbell Row",
    blockKind: "compound",
    movementPattern: "pull-horizontal",
    compatibleSplitDayTypes: ["pull", "back", "upper", "full-body"],
    goalTags: ["strength", "aesthetics", "general"],
    restrictionTags: ["low-back-stress"],
  },
  {
    id: "front-squat",
    name: "Front Squat",
    blockKind: "compound",
    movementPattern: "squat",
    compatibleSplitDayTypes: ["legs", "lower", "athletic-hybrid"],
    goalTags: ["strength", "athleticism"],
    restrictionTags: ["knee-stress"],
  },
  {
    id: "trap-bar-deadlift",
    name: "Trap Bar Deadlift",
    blockKind: "compound",
    movementPattern: "hinge",
    compatibleSplitDayTypes: ["legs", "lower", "full-body", "athletic-hybrid"],
    goalTags: ["strength", "athleticism", "general"],
    restrictionTags: ["low-back-stress"],
  },
  {
    id: "incline-dumbbell-press",
    name: "Incline Dumbbell Press",
    blockKind: "compound",
    movementPattern: "push-horizontal",
    compatibleSplitDayTypes: ["push", "chest", "upper"],
    goalTags: ["aesthetics", "general"],
  },
  {
    id: "pull-up",
    name: "Pull-Up",
    blockKind: "compound",
    movementPattern: "pull-vertical",
    compatibleSplitDayTypes: ["pull", "back", "upper", "full-body", "athletic-hybrid"],
    goalTags: ["strength", "aesthetics", "athleticism", "general"],
    sportTags: ["calisthenics"],
  },
  {
    id: "goblet-squat",
    name: "Goblet Squat",
    blockKind: "compound",
    movementPattern: "squat",
    compatibleSplitDayTypes: ["legs", "lower", "full-body"],
    goalTags: ["general", "weight-loss", "aesthetics"],
    restrictionTags: ["knee-stress"],
  },
  {
    id: "romanian-deadlift",
    name: "Romanian Deadlift",
    blockKind: "compound",
    movementPattern: "hinge",
    compatibleSplitDayTypes: ["legs", "lower", "full-body"],
    goalTags: ["strength", "aesthetics", "athleticism"],
    restrictionTags: ["low-back-stress"],
  },
  {
    id: "push-up",
    name: "Push-Up",
    blockKind: "compound",
    movementPattern: "push-horizontal",
    compatibleSplitDayTypes: ["push", "chest", "upper", "full-body"],
    goalTags: ["general", "aesthetics", "weight-loss"],
    sportTags: ["calisthenics"],
  },
  {
    id: "bodyweight-squat",
    name: "Bodyweight Squat",
    blockKind: "compound",
    movementPattern: "squat",
    compatibleSplitDayTypes: ["legs", "lower", "full-body"],
    goalTags: ["general", "weight-loss"],
    sportTags: ["calisthenics"],
  },
  {
    id: "dip",
    name: "Dip",
    blockKind: "compound",
    movementPattern: "push-horizontal",
    compatibleSplitDayTypes: ["push", "chest", "arms", "upper"],
    goalTags: ["aesthetics", "strength"],
    sportTags: ["calisthenics"],
  },
  {
    id: "inverted-row",
    name: "Inverted Row",
    blockKind: "compound",
    movementPattern: "pull-horizontal",
    compatibleSplitDayTypes: ["pull", "back", "upper", "full-body"],
    goalTags: ["general", "aesthetics"],
    sportTags: ["calisthenics"],
  },
  {
    id: "dumbbell-lateral-raise",
    name: "Dumbbell Lateral Raise",
    blockKind: "accessory",
    movementPattern: "push-vertical",
    compatibleSplitDayTypes: ["shoulders", "upper", "push"],
    goalTags: ["aesthetics"],
    restrictionTags: ["overhead"],
  },
  {
    id: "bicep-curl",
    name: "Bicep Curl",
    blockKind: "accessory",
    movementPattern: "pull-horizontal",
    compatibleSplitDayTypes: ["arms", "upper", "pull"],
    goalTags: ["aesthetics"],
  },
  {
    id: "tricep-pushdown",
    name: "Tricep Pushdown",
    blockKind: "accessory",
    movementPattern: "push-horizontal",
    compatibleSplitDayTypes: ["arms", "upper", "push"],
    goalTags: ["aesthetics"],
  },
  {
    id: "walking-lunge",
    name: "Walking Lunge",
    blockKind: "accessory",
    movementPattern: "locomotion",
    compatibleSplitDayTypes: ["legs", "lower", "athletic-hybrid"],
    goalTags: ["general", "athleticism", "aesthetics"],
    restrictionTags: ["knee-stress"],
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldown",
    blockKind: "accessory",
    movementPattern: "pull-vertical",
    compatibleSplitDayTypes: ["pull", "back", "upper"],
    goalTags: ["aesthetics", "general"],
  },
  {
    id: "leg-extension",
    name: "Leg Extension",
    blockKind: "accessory",
    movementPattern: "squat",
    compatibleSplitDayTypes: ["legs", "lower"],
    goalTags: ["aesthetics"],
    restrictionTags: ["knee-stress"],
  },
  {
    id: "leg-curl",
    name: "Leg Curl",
    blockKind: "accessory",
    movementPattern: "hinge",
    compatibleSplitDayTypes: ["legs", "lower"],
    goalTags: ["aesthetics"],
  },
  {
    id: "cable-chest-fly",
    name: "Cable Chest Fly",
    blockKind: "accessory",
    movementPattern: "push-horizontal",
    compatibleSplitDayTypes: ["chest", "push", "upper"],
    goalTags: ["aesthetics"],
  },
  {
    id: "face-pull",
    name: "Face Pull",
    blockKind: "accessory",
    movementPattern: "pull-horizontal",
    compatibleSplitDayTypes: ["shoulders", "pull", "upper", "back"],
    goalTags: ["aesthetics", "general", "athleticism"],
    restrictionTags: ["overhead"],
  },
  {
    id: "dumbbell-shoulder-press",
    name: "Dumbbell Shoulder Press",
    blockKind: "accessory",
    movementPattern: "push-vertical",
    compatibleSplitDayTypes: ["shoulders", "push", "upper"],
    goalTags: ["strength", "aesthetics", "general"],
    restrictionTags: ["overhead"],
  },
  {
    id: "seated-cable-row",
    name: "Seated Cable Row",
    blockKind: "accessory",
    movementPattern: "pull-horizontal",
    compatibleSplitDayTypes: ["back", "pull", "upper"],
    goalTags: ["aesthetics", "general", "strength"],
    restrictionTags: ["low-back-stress"],
  },
  {
    id: "plank",
    name: "Plank",
    blockKind: "core",
    movementPattern: "isometric",
    compatibleSplitDayTypes: ["full-body", "athletic-hybrid"],
    goalTags: ["general", "strength", "aesthetics"],
  },
  {
    id: "hanging-leg-raise",
    name: "Hanging Leg Raise",
    blockKind: "core",
    movementPattern: "isometric",
    compatibleSplitDayTypes: ["full-body", "athletic-hybrid"],
    goalTags: ["aesthetics", "athleticism"],
    restrictionTags: ["overhead"],
  },
  {
    id: "cable-woodchopper",
    name: "Cable Woodchopper",
    blockKind: "core",
    movementPattern: "rotation",
    compatibleSplitDayTypes: ["full-body", "athletic-hybrid"],
    goalTags: ["athleticism", "aesthetics"],
    restrictionTags: ["low-back-stress"],
  },
  {
    id: "russian-twist",
    name: "Russian Twist",
    blockKind: "core",
    movementPattern: "rotation",
    compatibleSplitDayTypes: ["full-body"],
    goalTags: ["aesthetics", "general"],
    restrictionTags: ["low-back-stress"],
  },
  {
    id: "dead-bug",
    name: "Dead Bug",
    blockKind: "core",
    movementPattern: "isometric",
    compatibleSplitDayTypes: ["full-body"],
    goalTags: ["general", "weight-loss", "athleticism"],
  },
  {
    id: "side-plank",
    name: "Side Plank",
    blockKind: "core",
    movementPattern: "isometric",
    compatibleSplitDayTypes: ["full-body"],
    goalTags: ["general", "athleticism"],
  },
  {
    id: "ab-wheel-rollout",
    name: "Ab Wheel Rollout",
    blockKind: "core",
    movementPattern: "isometric",
    compatibleSplitDayTypes: ["full-body", "athletic-hybrid"],
    goalTags: ["strength", "aesthetics", "athleticism"],
    restrictionTags: ["low-back-stress"],
  },
  {
    id: "kettlebell-swing",
    name: "Kettlebell Swing",
    blockKind: "conditioning",
    movementPattern: "hinge",
    compatibleSplitDayTypes: ["full-body", "athletic-hybrid"],
    goalTags: ["conditioning", "aesthetics", "athleticism"],
    restrictionTags: ["low-back-stress"],
  },
  {
    id: "sled-push",
    name: "Sled Push",
    blockKind: "conditioning",
    movementPattern: "locomotion",
    compatibleSplitDayTypes: ["full-body", "legs", "athletic-hybrid"],
    goalTags: ["conditioning", "aesthetics", "athleticism"],
    restrictionTags: ["knee-stress"],
  },
  {
    id: "battle-ropes",
    name: "Battle Ropes",
    blockKind: "conditioning",
    movementPattern: "push-horizontal",
    compatibleSplitDayTypes: ["full-body", "athletic-hybrid"],
    goalTags: ["conditioning", "aesthetics"],
  },
  {
    id: "jump-rope",
    name: "Jump Rope",
    blockKind: "conditioning",
    movementPattern: "jump",
    compatibleSplitDayTypes: ["full-body", "athletic-hybrid"],
    goalTags: ["conditioning", "weight-loss", "aesthetics", "athleticism"],
    restrictionTags: ["high-impact"],
  },
  {
    id: "assault-bike-sprints",
    name: "Assault Bike Sprints",
    blockKind: "conditioning",
    movementPattern: "locomotion",
    compatibleSplitDayTypes: ["full-body"],
    goalTags: ["conditioning", "weight-loss"],
  },
  {
    id: "agility-ladder-drills",
    name: "Agility Ladder Drills",
    blockKind: "conditioning",
    movementPattern: "locomotion",
    compatibleSplitDayTypes: ["athletic-hybrid", "legs"],
    goalTags: ["athleticism", "conditioning"],
    sportTags: ["agility"],
  },
  {
    id: "lateral-bound-skater-jumps",
    name: "Lateral Bound (Skater Jumps)",
    blockKind: "conditioning",
    movementPattern: "jump",
    compatibleSplitDayTypes: ["athletic-hybrid", "legs"],
    goalTags: ["athleticism", "conditioning"],
    sportTags: ["agility", "sprinting"],
    restrictionTags: ["knee-stress", "high-impact"],
  },
  {
    id: "mountain-climbers",
    name: "Mountain Climbers",
    blockKind: "conditioning",
    movementPattern: "locomotion",
    compatibleSplitDayTypes: ["full-body", "athletic-hybrid"],
    goalTags: ["conditioning", "weight-loss", "athleticism"],
    sportTags: ["calisthenics"],
  },
  {
    id: "wrestling-live-drilling",
    name: "Wrestling Live Drilling",
    blockKind: "skill",
    movementPattern: "skill-drill",
    compatibleSplitDayTypes: ["athletic-hybrid"],
    goalTags: ["athleticism", "conditioning"],
    sportTags: ["wrestling", "combat-sports"],
  },
  {
    id: "shadow-boxing-combat-footwork",
    name: "Shadow Boxing / Combat Footwork",
    blockKind: "skill",
    movementPattern: "skill-drill",
    compatibleSplitDayTypes: ["athletic-hybrid"],
    goalTags: ["athleticism", "conditioning"],
    sportTags: ["combat-sports"],
  },
  {
    id: "sprint-mechanics-drills",
    name: "Sprint Mechanics Drills",
    blockKind: "skill",
    movementPattern: "skill-drill",
    compatibleSplitDayTypes: ["athletic-hybrid", "legs"],
    goalTags: ["athleticism"],
    sportTags: ["sprinting"],
  },
  {
    id: "swim-technique-drills",
    name: "Swim Technique Drills",
    blockKind: "skill",
    movementPattern: "skill-drill",
    compatibleSplitDayTypes: ["athletic-hybrid"],
    goalTags: ["athleticism", "conditioning"],
    sportTags: ["swimming"],
  },
  {
    id: "mobility-joint-prep-flow",
    name: "Mobility/Joint Prep Flow",
    blockKind: "skill",
    movementPattern: "skill-drill",
    compatibleSplitDayTypes: ["athletic-hybrid"],
    goalTags: ["athleticism", "general"],
  },
];
