"use client";

import { useState } from "react";
import { generatePlan } from "@/lib/planGenerator";
import type { Plan } from "@/lib/planGenerator";
import type { Diet, Goal, IntakeData, Sex, Split } from "@/types/intake";

// TODO: When plan assembly is added, keep an Aesthetics secondary goal modest when Conditioning is primary.

const INITIAL_DATA: IntakeData = {
  name: "", age: null, sex: "", heightFt: null, heightIn: null, weight: null,
  highSchoolSports: [], otherSport: "", favoriteActivities: [], favoriteActivityOther: "",
  primaryGoal: "", primaryAestheticsAreas: [], secondaryGoal: "", secondaryAestheticsAreas: [],
  daysPerWeek: null, hoursPerDay: null, trainingSplit: "", trainingMethods: [], sportSkillSports: [],
  trainingRestrictions: "", sportSkillOther: "", dietPlan: "", dietPlanOther: "", dietaryRestrictions: "",
};

const HS_SPORTS = ["Football", "Track & Field", "Cross Country", "Basketball", "Soccer", "Baseball", "Wrestling", "Volleyball", "Softball", "Tennis", "Swim & Dive", "Golf", "Lacrosse", "Gymnastics", "Other"];
const ACTIVITIES = ["Weightlifting", "Calisthenics", "Plyometrics", "Agility training", "Stability & Mobility training", "Distance Running", "Sprinting", "Swimming", "Combat Sports", "Other"];
const AESTHETICS = ["Defined shoulders", "Chest", "Back", "Abs", "Legs", "Facial features / jawline"];
const GOALS: { value: Exclude<Goal, "">; label: string }[] = [
  { value: "strength", label: "Build strength" }, { value: "aesthetics", label: "Aesthetics" },
  { value: "weight-loss", label: "Lose weight" }, { value: "conditioning", label: "Conditioning" },
  { value: "athleticism", label: "Athleticism" }, { value: "general", label: "General" },
];
const SPLITS: { value: Exclude<Split, "">; label: string }[] = [
  { value: "full-body", label: "Full body" }, { value: "upper-lower", label: "Upper / Lower" },
  { value: "push-pull-legs", label: "Push / Pull / Legs" }, { value: "body-part-split", label: "Body part split" },
  { value: "athletic-hybrid", label: "Athletic Hybrid" },
];
const METHODS = ["Free weight training", "Bodyweight training", "Cardio", "Sport-specific skill work", "Hybrid"];
const DIETS: { value: Exclude<Diet, "">; label: string }[] = [
  { value: "none", label: "None" }, { value: "vegetarian", label: "Vegetarian" },
  { value: "protein-prioritization", label: "Protein prioritization" }, { value: "carbohydrate-prioritization", label: "Carbohydrate prioritization" }, { value: "other", label: "Other" },
];
const STEPS = [
  { title: "Biometrics", description: "The basics about you" }, { title: "Athletic History", description: "Your sports and activities" },
  { title: "Goals", description: "What you want to accomplish" }, { title: "Preferences", description: "How you like to train" },
  { title: "Diet", description: "How you fuel your training" }, { title: "Review", description: "Check everything before submitting" },
];

const toggle = (items: string[], item: string) => items.includes(item) ? items.filter((current) => current !== item) : [...items, item];
const toNumber = (value: string) => value === "" ? null : Number(value);
const list = (items: string[]) => items.length ? items.join(", ") : "None";

export default function GetStartedPage() {
  const [step, setStep] = useState(0);
  const [data, setData] = useState<IntakeData>(INITIAL_DATA);
  const [plan, setPlan] = useState<Plan | null>(null);
  const [weightError, setWeightError] = useState("");
  const update = <K extends keyof IntakeData>(field: K, value: IntakeData[K]) => setData((previous) => ({ ...previous, [field]: value }));
  const toggleSkillSport = (sport: string) => update("sportSkillSports", data.sportSkillSports.includes(sport) ? data.sportSkillSports.filter((current) => current !== sport) : data.sportSkillSports.length < 2 ? [...data.sportSkillSports, sport] : data.sportSkillSports);
  const toggleTrainingMethod = (method: string) => {
    const nextMethods = toggle(data.trainingMethods, method);
    update("trainingMethods", nextMethods);
    if (method === "Sport-specific skill work" && !nextMethods.includes(method)) {
      update("sportSkillSports", []);
      update("sportSkillOther", "");
    }
  };
  const selectedSport = (name: string) => data.highSchoolSports.find((sport) => sport.name === name);
  const toggleSport = (name: string) => update("highSchoolSports", selectedSport(name) ? data.highSchoolSports.filter((sport) => sport.name !== name) : [...data.highSchoolSports, { name, years: null }]);
  const updateYears = (name: string, years: number | null) => update("highSchoolSports", data.highSchoolSports.map((sport) => sport.name === name ? { ...sport, years } : sport));
  const selectGoal = (field: "primaryGoal" | "secondaryGoal", value: Exclude<Goal, "">) => {
    const nextGoal = data[field] === value ? "" : value;
    update(field, nextGoal);
    if (nextGoal !== "aesthetics") update(field === "primaryGoal" ? "primaryAestheticsAreas" : "secondaryAestheticsAreas", []);
  };
  const valid = () => {
    if (step === 0) return Boolean(data.name.trim() && data.age && data.age > 0 && data.sex && data.heightFt !== null && data.heightIn !== null && data.weight && data.weight > 0);
    if (step === 1) return Boolean(data.highSchoolSports.length && data.highSchoolSports.every((sport) => sport.years !== null && sport.years >= 1 && sport.years <= 4) && (!selectedSport("Other") || data.otherSport.trim()) && data.favoriteActivities.length && (!data.favoriteActivities.includes("Other") || data.favoriteActivityOther.trim()));
    if (step === 2) return Boolean(data.primaryGoal && data.daysPerWeek && data.daysPerWeek >= 1 && data.daysPerWeek <= 7 && data.hoursPerDay && data.hoursPerDay >= 0.25 && data.hoursPerDay <= 3);
    if (step === 3) return Boolean(data.trainingSplit && data.trainingMethods.length && (!data.sportSkillSports.includes("Other") || data.sportSkillOther.trim()));
    if (step === 4) return Boolean(data.dietPlan && (data.dietPlan !== "other" || data.dietPlanOther.trim()));
    return true;
  };
  const next = () => { if (step < STEPS.length - 1 && valid()) setStep(step + 1); };
  const back = () => { if (step > 0) setStep(step - 1); };
  const submit = () => setPlan(generatePlan(data));
  const input = "w-full rounded-lg border border-zinc-300 bg-white px-3.5 py-2.5 text-base outline-none transition-colors focus:border-zinc-900 focus:ring-2 focus:ring-zinc-900/10 dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-100 dark:focus:border-zinc-400";
  const label = "block text-sm font-medium mb-1.5";
  const card = (active: boolean) => `flex cursor-pointer items-center gap-3 rounded-lg border px-4 py-3 text-left transition-all ${active ? "border-zinc-900 bg-zinc-900/5 ring-2 ring-zinc-900/10 dark:border-zinc-400 dark:bg-zinc-400/10" : "border-zinc-200 bg-white hover:border-zinc-400 dark:border-zinc-700 dark:bg-zinc-900"}`;
  const goalOptions = (field: "primaryGoal" | "secondaryGoal", value: Goal) => <div className="space-y-2">{GOALS.map((goal) => <label key={goal.value} className={card(value === goal.value)}><input type="radio" name={field} checked={value === goal.value} onChange={() => selectGoal(field, goal.value)} className="h-4 w-4 accent-zinc-900" /><span className="text-sm">{goal.label}</span></label>)}</div>;
  const areas = (field: "primaryAestheticsAreas" | "secondaryAestheticsAreas", show: boolean) => show ? <div className="mt-3 grid grid-cols-1 gap-2 rounded-lg border border-zinc-200 p-3 sm:grid-cols-2 dark:border-zinc-700">{AESTHETICS.map((area) => <label key={area} className={card(data[field].includes(area))}><input type="checkbox" checked={data[field].includes(area)} onChange={() => update(field, toggle(data[field], area))} className="h-4 w-4 accent-zinc-900" /><span className="text-sm">{area}</span></label>)}</div> : null;

  const renderStep = () => {
    if (step === 0) return <div className="space-y-5"><div><label htmlFor="name" className={label}>Name</label><input id="name" type="text" className={input} value={data.name} onChange={(event) => update("name", event.target.value)} /></div><div className="grid grid-cols-2 gap-4"><div><label htmlFor="age" className={label}>Age</label><input id="age" type="number" min={1} className={input} value={data.age ?? ""} onChange={(event) => update("age", toNumber(event.target.value))} /></div><div><label htmlFor="weight" className={label}>Weight (lbs)</label><input id="weight" type="number" min={1} step="0.1" aria-invalid={Boolean(weightError)} aria-describedby="weight-error" className={input} value={data.weight ?? ""} onChange={(event) => { update("weight", toNumber(event.target.value)); setWeightError(event.currentTarget.validity.valid ? "" : "Enter a weight of at least 1 lb with no more than one decimal place."); }} />{weightError ? <p id="weight-error" className="mt-1.5 text-sm text-red-600" role="alert">{weightError}</p> : null}</div></div><div><label htmlFor="sex" className={label}>Sex</label><select id="sex" className={input} value={data.sex} onChange={(event) => update("sex", event.target.value as Sex)}><option value="">Select...</option><option value="male">Male</option><option value="female">Female</option><option value="prefer-not-to-say">Prefer not to say</option></select></div><div><label className={label}>Height</label><div className="grid grid-cols-2 gap-3"><input aria-label="Height in feet" type="number" min={0} max={8} placeholder="Feet" className={input} value={data.heightFt ?? ""} onChange={(event) => update("heightFt", toNumber(event.target.value))} /><input aria-label="Height in inches" type="number" min={0} max={11} placeholder="Inches" className={input} value={data.heightIn ?? ""} onChange={(event) => update("heightIn", toNumber(event.target.value))} /></div></div></div>;
    if (step === 1) return <div className="space-y-8"><section><h3 className="mb-1 text-base font-semibold">Part I: High-school sports</h3><p className="mb-3 text-sm text-zinc-500">Select each sport and enter the years played.</p><div className="space-y-2">{HS_SPORTS.map((sport) => { const record = selectedSport(sport); return <div key={sport} className={`rounded-lg border p-3 ${record ? "border-zinc-900 dark:border-zinc-400" : "border-zinc-200 dark:border-zinc-700"}`}><label className="flex cursor-pointer items-center gap-3"><input type="checkbox" checked={Boolean(record)} onChange={() => toggleSport(sport)} className="h-4 w-4 accent-zinc-900" /><span className="text-sm">{sport}</span></label>{record ? <div className="mt-3 flex items-center gap-2 pl-7"><label htmlFor={`years-${sport}`} className="text-xs text-zinc-500">Years played</label><input id={`years-${sport}`} type="number" min={1} max={4} step={1} className="w-24 rounded-md border border-zinc-300 bg-white px-2 py-1.5 text-sm" value={record.years ?? ""} onChange={(event) => updateYears(sport, toNumber(event.target.value))} /></div> : null}</div>; })}</div>{selectedSport("Other") ? <input type="text" placeholder="Other sport" className={`${input} mt-3`} value={data.otherSport} onChange={(event) => update("otherSport", event.target.value)} /> : null}</section><section><h3 className="mb-1 text-base font-semibold">Part II: Favorite athletic activities</h3><p className="mb-3 text-sm text-zinc-500">Select all that sound like you.</p><div className="grid grid-cols-1 gap-2 sm:grid-cols-2">{ACTIVITIES.map((activity) => <label key={activity} className={card(data.favoriteActivities.includes(activity))}><input type="checkbox" checked={data.favoriteActivities.includes(activity)} onChange={() => update("favoriteActivities", toggle(data.favoriteActivities, activity))} className="h-4 w-4 accent-zinc-900" /><span className="text-sm">{activity}</span></label>)}</div>{data.favoriteActivities.includes("Other") ? <input type="text" placeholder="Other activity" className={`${input} mt-3`} value={data.favoriteActivityOther} onChange={(event) => update("favoriteActivityOther", event.target.value)} /> : null}</section></div>;
    if (step === 2) return <div className="space-y-8"><section><h3 className="mb-1 text-base font-semibold">Part I: Primary goal</h3><p className="mb-3 text-sm text-zinc-500">Choose one primary goal.</p>{goalOptions("primaryGoal", data.primaryGoal)}{areas("primaryAestheticsAreas", data.primaryGoal === "aesthetics")}</section><section><h3 className="mb-1 text-base font-semibold">Optional secondary goal</h3><p className="mb-3 text-sm text-zinc-500">This will be lower priority than your primary goal.</p>{goalOptions("secondaryGoal", data.secondaryGoal)}{areas("secondaryAestheticsAreas", data.secondaryGoal === "aesthetics")}</section><section><h3 className="mb-3 text-base font-semibold">Part II: Time available</h3><div className="grid grid-cols-2 gap-4"><div><label htmlFor="days" className={label}>Days per week</label><input id="days" type="number" min={1} max={7} step={1} className={input} value={data.daysPerWeek ?? ""} onChange={(event) => update("daysPerWeek", toNumber(event.target.value))} /></div><div><label htmlFor="hours" className={label}>Hours per day</label><input id="hours" type="number" min={0.25} max={3} step={0.25} className={input} value={data.hoursPerDay ?? ""} onChange={(event) => update("hoursPerDay", toNumber(event.target.value))} /></div></div></section></div>;
    if (step === 3) return <div className="space-y-8"><section><h3 className="mb-3 text-base font-semibold">Part I: Training preferences</h3><label className={label}>Preferred training split</label><div className="space-y-2">{SPLITS.map((split) => <label key={split.value} className={card(data.trainingSplit === split.value)}><input type="radio" name="split" checked={data.trainingSplit === split.value} onChange={() => update("trainingSplit", split.value)} className="h-4 w-4 accent-zinc-900" /><span className="text-sm">{split.label}</span></label>)}</div><label className={`${label} mt-6`}>Preferred training methods</label><div className="space-y-2">{METHODS.map((method) => <label key={method} className={card(data.trainingMethods.includes(method))}><input type="checkbox" checked={data.trainingMethods.includes(method)} onChange={() => toggleTrainingMethod(method)} className="h-4 w-4 accent-zinc-900" /><span className="text-sm">{method}</span></label>)}</div>{data.trainingMethods.includes("Sport-specific skill work") ? <div className="mt-3"><label className={label}>Sports for skill work (choose up to 2)</label><div className="grid grid-cols-1 gap-2 sm:grid-cols-2">{HS_SPORTS.map((sport) => <label key={sport} className={card(data.sportSkillSports.includes(sport))}><input type="checkbox" checked={data.sportSkillSports.includes(sport)} onChange={() => toggleSkillSport(sport)} className="h-4 w-4 accent-zinc-900" /><span className="text-sm">{sport}</span></label>)}</div>{data.sportSkillSports.includes("Other") ? <input type="text" placeholder="Other sport" className={`${input} mt-3`} value={data.sportSkillOther} onChange={(event) => update("sportSkillOther", event.target.value)} /> : null}</div> : null}</section><section><h3 className="mb-1 text-base font-semibold">Part II: Training restrictions</h3><p className="mb-3 text-sm text-zinc-500">Include injuries, equipment limits, exercises to avoid, or anything else we should know.</p><textarea className={`${input} min-h-32 resize-y`} value={data.trainingRestrictions} onChange={(event) => update("trainingRestrictions", event.target.value)} /></section></div>;
    if (step === 4) return <div className="space-y-8"><section><h3 className="mb-3 text-base font-semibold">Part I: Preferred diet plan</h3><div className="space-y-2">{DIETS.map((diet) => <label key={diet.value} className={card(data.dietPlan === diet.value)}><input type="radio" name="diet" checked={data.dietPlan === diet.value} onChange={() => { update("dietPlan", diet.value); if (diet.value !== "other") update("dietPlanOther", ""); }} className="h-4 w-4 accent-zinc-900" /><span className="text-sm">{diet.label}</span></label>)}</div>{data.dietPlan === "other" ? <input type="text" placeholder="Describe your preferred diet plan" className={`${input} mt-3`} value={data.dietPlanOther} onChange={(event) => update("dietPlanOther", event.target.value)} /> : null}</section><section><h3 className="mb-1 text-base font-semibold">Part II: Dietary restrictions</h3><p className="mb-3 text-sm text-zinc-500">List allergies, intolerances, or other dietary restrictions.</p><textarea className={`${input} min-h-32 resize-y`} value={data.dietaryRestrictions} onChange={(event) => update("dietaryRestrictions", event.target.value)} /></section></div>;
    return <div className="space-y-4"><Review title="Biometrics" edit={() => setStep(0)} items={[["Name", data.name], ["Age", `${data.age ?? "—"}`], ["Sex", data.sex || "—"], ["Height", data.heightFt === null || data.heightIn === null ? "—" : `${data.heightFt}'${data.heightIn}"`], ["Weight", data.weight === null ? "—" : `${data.weight} lbs`]]} /><Review title="Athletic History" edit={() => setStep(1)} items={[["HS sports", data.highSchoolSports.map((sport) => `${sport.name === "Other" ? data.otherSport || "Other" : sport.name} (${sport.years ?? "?"} yr)`).join(", ") || "None"], ["Favorite activities", data.favoriteActivities.map((activity) => activity === "Other" ? data.favoriteActivityOther || "Other" : activity).join(", ") || "None"]]} /><Review title="Goals" edit={() => setStep(2)} items={[["Primary", GOALS.find((goal) => goal.value === data.primaryGoal)?.label || "—"], ...(data.primaryGoal === "aesthetics" ? [["Primary aesthetics", list(data.primaryAestheticsAreas)] as [string, string]] : []), ["Secondary", GOALS.find((goal) => goal.value === data.secondaryGoal)?.label || "None"], ...(data.secondaryGoal === "aesthetics" ? [["Secondary aesthetics", list(data.secondaryAestheticsAreas)] as [string, string]] : []), ["Availability", `${data.daysPerWeek ?? "—"} days / ${data.hoursPerDay ?? "—"} hours`]]} /><Review title="Preferences" edit={() => setStep(3)} items={[["Split", SPLITS.find((split) => split.value === data.trainingSplit)?.label || "—"], ["Methods", list(data.trainingMethods)], ...(data.trainingMethods.includes("Sport-specific skill work") ? [["Skill sports", list(data.sportSkillSports.map((sport) => sport === "Other" ? data.sportSkillOther || "Other" : sport))] as [string, string]] : []), ["Restrictions", data.trainingRestrictions || "None"]]} /><Review title="Diet" edit={() => setStep(4)} items={[["Plan", DIETS.find((diet) => diet.value === data.dietPlan)?.label || "—"], ["Other plan", data.dietPlanOther || "None"], ["Restrictions / allergies", data.dietaryRestrictions || "None"]]} /></div>;
  };

  return <div className="flex flex-1 flex-col bg-zinc-50 dark:bg-black"><main className="mx-auto flex w-full max-w-lg flex-1 flex-col px-4 py-8 sm:px-6"><div className="mb-2 text-center"><h1 className="text-2xl font-bold tracking-tight text-zinc-900 dark:text-zinc-50">Let&apos;s Get You Started</h1><p className="mt-1 text-sm text-zinc-500 dark:text-zinc-400">Tell us about your background so we can build your plan.</p></div><div className="mb-8 mt-6"><div className="flex items-center justify-between">{STEPS.map((current, index) => <div key={current.title} className="flex flex-1 items-center"><button type="button" onClick={() => index <= step && setStep(index)} className="flex flex-col items-center" aria-label={`Go to ${current.title}`}><span className={`flex h-8 w-8 items-center justify-center rounded-full text-xs font-semibold ${index < step ? "bg-zinc-900 text-white" : index === step ? "bg-zinc-900 text-white ring-2 ring-zinc-900/20 ring-offset-2" : "bg-zinc-200 text-zinc-500"}`}>{index < step ? "✓" : index + 1}</span><span className="mt-1 hidden text-[10px] font-medium text-zinc-500 sm:block">{current.title}</span></button>{index < STEPS.length - 1 ? <div className={`mx-1 h-0.5 flex-1 ${index < step ? "bg-zinc-900" : "bg-zinc-200"}`} /> : null}</div>)}</div></div><div className="flex-1"><h2 className="mb-1 text-lg font-semibold text-zinc-900 dark:text-zinc-50">{STEPS[step].title}</h2><p className="mb-5 text-sm text-zinc-500 dark:text-zinc-400">{STEPS[step].description}</p>{renderStep()}</div><div className="mt-8 flex gap-3 border-t border-zinc-200 pt-5 dark:border-zinc-800">{step > 0 ? <button type="button" onClick={back} className="flex-1 rounded-lg border border-zinc-300 bg-white px-4 py-3 text-sm font-medium text-zinc-700">Back</button> : null}{step < STEPS.length - 1 ? <button type="button" onClick={next} disabled={!valid()} className="flex-1 rounded-lg bg-zinc-900 px-4 py-3 text-sm font-medium text-white disabled:cursor-not-allowed disabled:opacity-40">Next</button> : <button type="button" onClick={submit} className="flex-1 rounded-lg bg-zinc-900 px-4 py-3 text-sm font-medium text-white">Submit</button>}</div>{plan ? <pre className="mt-6 overflow-x-auto rounded-lg bg-zinc-900 p-4 text-xs leading-relaxed text-zinc-100">{JSON.stringify(plan, null, 2)}</pre> : null}</main></div>;
}

function Review({ title, edit, items }: { title: string; edit: () => void; items: [string, string][] }) {
  return <section className="rounded-lg border border-zinc-200 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900"><div className="mb-2 flex items-center justify-between"><h3 className="text-sm font-semibold text-zinc-900 dark:text-zinc-100">{title}</h3><button type="button" onClick={edit} className="text-xs font-medium text-zinc-500 hover:text-zinc-900">Edit</button></div><dl className="space-y-1">{items.map(([key, value]) => <div key={key} className="flex justify-between gap-4 text-sm"><dt className="text-zinc-500">{key}</dt><dd className="text-right font-medium text-zinc-900 dark:text-zinc-100">{value}</dd></div>)}</dl></section>;
}
